### ISSUE TITLE
install Error

### ISSUE THREAD

**Issue by neverlandgh** [SpectrumQT/XXMI-Launcher#60]
![Snipaste_2024-12-24_23-35-48](https://github.com/user-attachments/assets/2fdba2ad-6a07-4464-ae4c-8a20f6aabecc)

**Comment by neverlandgh** [comment]
XXMI Launcher Log

2024-12-24 23:46:15,392,392 root DEBUG App Start
2024-12-24 23:46:16,498,498 root DEBUG Arguments: Namespace(help=False, xxmi=None, nogui=False, update=False, msi=None, create_shortcut=None, uninstall=False)
2024-12-24 23:46:16,505,505 core.package_manager DEBUG Loaded package: Launcher
2024-12-24 23:46:16,505,505 core.package_manager DEBUG Loaded package: XXMI
2024-12-24 23:46:16,505,505 core.package_manager DEBUG Loaded package: XXMI
2024-12-24 23:46:16,505,505 core.package_manager DEBUG Loaded package: ZZMI
2024-12-24 23:46:16,506,506 core.event_manager DEBUG FIRED: PackageManagerEvents.VersionNotification(auto_update=True, package_states={'Launcher': PackageState(installed_version='1.2.0', latest_version='', skipped_version=''), 'XXMI': PackageState(installed_version='', latest_version='0.3.1', skipped_version=''), 'ZZMI': PackageState(installed_version='', latest_version='', skipped_version='')})
2024-12-24 23:46:16,515,515 core.event_manager DEBUG FIRED: ApplicationEvents.ConfigUpdate()
2024-12-24 23:46:16,767,767 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.ToggleImporter(importer_id='GIMI', index=-1, show=False)
2024-12-24 23:46:16,777,777 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.ToggleImporter(importer_id='SRMI', index=-1, show=False)
2024-12-24 23:46:16,787,787 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.ToggleImporter(importer_id='WWMI', index=-1, show=False)
2024-12-24 23:46:16,797,797 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.ToggleImporter(importer_id='ZZMI', index=0, show=True)
2024-12-24 23:46:16,806,806 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.ToggleImporter(importer_id='XXMI', index=-1, show=False)
2024-12-24 23:46:16,893,893 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.ToggleImporter(importer_id='XXMI', index=1, show=True)
2024-12-24 23:46:16,965,965 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.HoverImporter(importer_id='GIMI', hover=False)
2024-12-24 23:46:16,991,991 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.HoverImporter(importer_id='SRMI', hover=False)
2024-12-24 23:46:17,017,17 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.HoverImporter(importer_id='WWMI', hover=False)
2024-12-24 23:46:17,081,81 core.event_manager DEBUG FIRED: ApplicationEvents.Ready()
2024-12-24 23:46:17,081,81 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.StageUpdate(stage=<Stage.Ready: 1>)
2024-12-24 23:46:17,160,160 core.event_manager DEBUG FIRED: ApplicationEvents.LoadImporter(importer_id='ZZMI', reload=False)
2024-12-24 23:46:17,284,284 core.event_manager DEBUG FIRED: ApplicationEvents.ConfigUpdate()
2024-12-24 23:46:17,285,285 core.event_manager DEBUG FIRED: PackageManagerEvents.VersionNotification(auto_update=True, package_states={'Launcher': PackageState(installed_version='1.2.0', latest_version='', skipped_version=''), 'XXMI': PackageState(installed_version='', latest_version='0.3.1', skipped_version=''), 'ZZMI': PackageState(installed_version='', latest_version='', skipped_version='')})
2024-12-24 23:46:17,287,287 root DEBUG Core ready!
2024-12-24 23:46:17,394,394 core.event_manager DEBUG FIRED: ApplicationEvents.Ready()
2024-12-24 23:46:17,394,394 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.StageUpdate(stage=<Stage.Ready: 1>)
2024-12-24 23:46:18,286,286 root INFO System: {'OS': 'Microsoft Windows 11 专业版 10.0.26100', 'CPU': 'AMD Ryzen 5 3600X 6-Core Processor', 'RAM': '8.4/15.92 GB', 'GPU': 'NVIDIA GeForce RTX 2060', 'MB': 'MS-7B89'}      
2024-12-24 23:46:18,423,423 core.event_manager DEBUG FIRED: ModelImporterEvents.Install()
2024-12-24 23:46:18,423,423 core.event_manager DEBUG FIRED: ApplicationEvents.Update(no_install=False, force=True, reinstall=True, packages=['ZZMI'], silent=False, no_thread=False)
2024-12-24 23:46:18,423,423 core.package_manager DEBUG Initializing packages update (no_install=False, no_check=False, force=True, reinstall=True, silent=False, packages=['ZZMI'])...
2024-12-24 23:46:18,424,424 core.event_manager DEBUG FIRED: ApplicationEvents.Busy()
2024-12-24 23:46:18,455,455 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.StageUpdate(stage=<Stage.Busy: 2>)
2024-12-24 23:46:18,573,573 core.event_manager DEBUG FIRED: PackageManagerEvents.StartCheckUpdate()
2024-12-24 23:46:18,575,575 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): api.github.com:443
2024-12-24 23:46:19,212,212 urllib3.connectionpool DEBUG https://api.github.com:443 "GET /repos/SpectrumQT/3Dmigoto/releases/latest HTTP/11" 200 1775
2024-12-24 23:46:19,213,213 core.event_manager DEBUG FIRED: PackageManagerEvents.InitializeDownload()
2024-12-24 23:46:19,215,215 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.StageUpdate(stage=<Stage.Download: 3>)
2024-12-24 23:46:19,309,309 core.event_manager DEBUG FIRED: PackageManagerEvents.StartDownload(asset_name='XXMI-PACKAGE-v0.3.1.zip')
2024-12-24 23:46:19,314,314 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): github.com:443
2024-12-24 23:46:23,394,394 core.event_manager DEBUG FIRED: PackageManagerEvents.VersionNotification(auto_update=True, package_states={'Launcher': PackageState(installed_version='1.2.0', latest_version='', skipped_version=''), 'XXMI': PackageState(installed_version='', latest_version='0.3.1', skipped_version=''), 'ZZMI': PackageState(installed_version='', latest_version='', skipped_version='')})
2024-12-24 23:46:23,397,397 core.event_manager DEBUG FIRED: ApplicationEvents.Ready()
2024-12-24 23:46:23,398,398 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.StageUpdate(stage=<Stage.Ready: 1>)
2024-12-24 23:46:23,674,674 root ERROR Traceback (most recent call last):
  File "D:\Games\XXMI Launcher\Resources\Bin\urllib3\connection.py", line 199, in _new_conn
  File "D:\Games\XXMI Launcher\Resources\Bin\urllib3\util\connection.py", line 85, in create_connection
  File "D:\Games\XXMI Launcher\Resources\Bin\urllib3\util\connection.py", line 73, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Games\XXMI Launcher\Resources\Bin\urllib3\connectionpool.py", line 789, in urlopen
  File "D:\Games\XXMI Launcher\Resources\Bin\urllib3\connectionpool.py", line 466, in _make_request
  File "D:\Games\XXMI Launcher\Resources\Bin\urllib3\connectionpool.py", line 1095, in _validate_conn
  File "D:\Games\XXMI Launcher\Resources\Bin\urllib3\connection.py", line 693, in connect
  File "D:\Games\XXMI Launcher\Resources\Bin\urllib3\connection.py", line 216, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000018CE479CF50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Games\XXMI Launcher\Resources\Bin\requests\adapters.py", line 667, in send
  File "D:\Games\XXMI Launcher\Resources\Bin\urllib3\connectionpool.py", line 843, in urlopen
  File "D:\Games\XXMI Launcher\Resources\Bin\urllib3\util\retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /SpectrumQT/3Dmigoto/releases/download/v0.3.1/XXMI-PACKAGE-v0.3.1.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018CE479CF50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Games\XXMI Launcher\Resources\Bin\core\application.py", line 527, in wrap_errors
  File "D:\Games\XXMI Launcher\Resources\Bin\core\package_manager.py", line 504, in update_packages
  File "D:\Games\XXMI Launcher\Resources\Bin\core\package_manager.py", line 487, in update_packages
  File "D:\Games\XXMI Launcher\Resources\Bin\core\package_manager.py", line 541, in update_package
  File "D:\Games\XXMI Launcher\Resources\Bin\core\package_manager.py", line 299, in update
  File "D:\Games\XXMI Launcher\Resources\Bin\core\package_manager.py", line 174, in download_latest_version
  File "D:\Games\XXMI Launcher\Resources\Bin\core\package_manager.py", line 143, in download_latest_version_data
  File "D:\Games\XXMI Launcher\Resources\Bin\core\utils\github_client.py", line 62, in download_data
  File "D:\Games\XXMI Launcher\Resources\Bin\requests\api.py", line 73, in get
  File "D:\Games\XXMI Launcher\Resources\Bin\requests\api.py", line 59, in request
  File "D:\Games\XXMI Launcher\Resources\Bin\requests\sessions.py", line 589, in request
  File "D:\Games\XXMI Launcher\Resources\Bin\requests\sessions.py", line 703, in send
  File "D:\Games\XXMI Launcher\Resources\Bin\requests\adapters.py", line 700, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /SpectrumQT/3Dmigoto/releases/download/v0.3.1/XXMI-PACKAGE-v0.3.1.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018CE479CF50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

2024-12-24 23:46:25,339,339 gui.windows.message_window DEBUG Messagebox window closed
2024-12-24 23:46:25,364,364 gui.classes.windows DEBUG TopLevel closed
2024-12-24 23:46:25,464,464 core.event_manager DEBUG FIRED: ApplicationEvents.Ready()
2024-12-24 23:46:25,464,464 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.StageUpdate(stage=<Stage.Ready: 1>)
2024-12-24 23:46:26,225,225 core.event_manager DEBUG FIRED: ApplicationEvents.Close(delay=0)
2024-12-24 23:46:26,225,225 core.event_manager DEBUG FIRED: ApplicationEvents.Ready()
2024-12-24 23:46:26,225,225 core.event_manager DEBUG FIRED: GUIEvents.LauncherFrame.StageUpdate(stage=<Stage.Ready: 1>)
2024-12-24 23:46:26,301,301 gui.classes.windows DEBUG GUI stopped
2024-12-24 23:46:26,410,410 root DEBUG Joining threads...
2024-12-24 23:46:26,410,410 root DEBUG Joining watchdog thread...
2024-12-24 23:46:26,510,510 root DEBUG Saving config...
2024-12-24 23:46:26,511,511 root DEBUG App Exit

**Comment by SpectrumQT** [comment]
It's internet connection issue. Most likely it's caused by wrongly configured proxy or VPN.

**Comment by neverlandgh** [comment]
Because I was in China, the DNS resolution of github.com was polluted, and manually changing the hosts file solved the problem.
